dist: trusty
language: rust
services: docker
sudo: required
env:
  global:
  - CRATE_NAME=spotter
  - secure: Z9pAGqdjf+RGaRjkvpiijTKdJUDmc/Reh+8pfshNPFp4JabwAPxCoJHFitDx808eYUKQOjOy1AdZAoXSIfjHkz01MEv1cYBCImS+Jj9ngFOp6AW9y13vXXTnNlkfQDF4an//cOr16BgrBW5mfgzR3moWS4fmmAM5jplIUeKt/Ufvbi9D7iTltRSEe+Ucevdj3tuUUWS6hyHsQAA0NbjLcnLL+DJK0S7208ZKwgvWky5ozcfllEoN15CUkHOs+43neJjt3snmOUXTWVaNPYNL5D510AEclad2gzBBhRdguNZY4PA6Ad3/llmvTjl1LAPE3L9p6lfVnEyPG319OebC3IUblxeem3YCIGRG8C4ERVidnPoNkrP07GsHoPTk/DDDD5ta1FGK9wDK8GO050XCahcgcaHQk3S3hC+0M+ga8MrufSm2aIFZ7VQyPdQAU8Kd/oVMLOmJj3a5wRu1MKtBJuzH2To7Qcq7TfkNxn6TBDYotpQ85fGYqrFJvK/SMv5EKggISoPiVjqKFT1X4MpdEqGnnoZGzWi9FOHhpjFfaRHDhXkbmJumcDMZydLC7yCflfyGUNfWkpe5Dp/Wul64IOMw5riwcJ1r5XGAstcIdo82Ajz6HFzs6XwcL9oNkNM1GdeypsMk6BBhI4baMEdQehy7YD4rPwIVp703A303iEg=
matrix:
  include:
  - env: TARGET=x86_64-apple-darwin
    os: osx
  # - env: TARGET=x86_64-pc-windows-gnu
before_install:
- set -e
- rustup self update
install:
- sh ci/install.sh
- source ~/.cargo/env || true
script:
- bash ci/script.sh
after_script: set +e
before_deploy:
- sh ci/before_deploy.sh
deploy:
  api_key:
    secure: kGCho4FGA4kIXv4/UH3abdjnMETwh+syix1G5NBSJ6Z5l2vXwYH78uoRDSXTj/Wy5nRYlBZrm+awiGXVRktQpW8y8VFtnrBuVH76RsGPjw+Rd6BB4rIDjehw7UkkK73f6ajwwXkrlvmYA0YifX5B3laq0ChGJeFLHNjwA0blgtpLGkBZtYQ7qXZx9qXyHEiXfS+wwmuw300LeBLLztWZ5J1O9PmLiRKIUP6qKeCXLI/uQ4bFpey5WEfN0rnjHJWr41/xeBSROyP4TAnY+vc4GwX4Sh9I4T03BZ/X6eEsqtPa0XdEYZqFfNIfojMLgSv2X3RrkducWXAXfc80Ihn005jFj+9OeGiIOugjzmWY8GpuU5OMFQWtyJCCV/m9VK7iPoTRh9dTzZCJDS07O1VCiUCh6aD/hBbmLBCT5vyLOI2S1UaL0QdnQOQZOqbFEe7Td3L1UEsqfwJmvYbzxUk5Y+L50KqGnk8tR4xgt4jhnrw46LTbfBZIt77AlnBFZPHODJpGnubcx5ptopkZvOLYoDaz/GzkoltgBtq5A3aEG4b3/TCiYAvrgVpmTqbhHbs06TIuki6s+mmqanyXKv2Txj3O41MxQpSooxw1beY0LCpFu9RdiJGo4Zmo3Q7O2+ixj4HpK+WWTXHsfWckCBDNBuPiUqkcpuqyy1EmDyznNNI=
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  on:
    condition: "$TRAVIS_RUST_VERSION = stable"
    tags: true
  provider: releases
  skip_cleanup: true
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - master
notifications:
  email:
    on_success: never
